// -- MODULE DECLARATIONS -- //
mod base;
mod page_dragon_spiky_sfx;
mod page_dull_ending_black_bubble;
mod page_elder_hmm_bubble_angle;
mod page_eleven_years_red_smoke_narration;
mod page_headache_screaming_spiky_bubble;
mod page_hospital_gown_pattern_team_leader_bubble;
mod page_hospital_reception_wall_sign;
mod page_iv_drip_sedative_squeeze_sfx;
mod page_korean_gamers_365_days_continuous;
mod page_korean_scream_kkaaak_spiky_bubble;
mod page_marrow_cleansing_exhale_sfx;
mod page_meditating_martial_artist_vibration_sfx;
mod page_one_chance_fuzzy_bubble;
mod page_patient_endoscopy_heartbeat_sfx;
mod page_patient_greeting_doctor_exclamation;
mod page_physician_seok_treatment_bubble_centering;
mod page_polyp_discovered_spiky_punctuation_bubble;
mod page_red_dragon_destia_floor_48;
mod page_snake_skewer_crackle_sfx_tadak;
mod page_spring_up_couch_worry_sfx;
mod page_suddenly_reality_check_bottom_narration;
mod page_talk_like_that_bottom_narration;
mod page_yu_family_spear_technique_slash;

